inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

RSpec/ExampleLength:
  Max: 30

Layout/EndOfLine:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

RSpec/InstanceVariable:
  Exclude:
    - '**/*_spec.rb'